### ISSUE TITLE
能否增加一些期刊文献网站的支持？

### ISSUE THREAD

**Issue by jierme** [Whilconn/one-toc#2]
如题，例如 pubmed 上文献全文页面，要是能支持显示目录就好了。
举个例子：https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6742634/

**Comment by Whilconn** [comment]
> 如题，例如 pubmed 上文献全文页面，要是能支持显示目录就好了。 举个例子：https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6742634/

@jierme 没有默认支持这些网站，但是可以通过修改匹配规则支持，两种改法：
- 方法1：按需匹配指定网站
  - 比如你想在 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6742634/ 这个网站上开启OneToc的目录 ，可以在匹配规则里加一条规则 `*www.ncbi.nlm.nih.gov/**`

- 方法2：匹配所有网站，把匹配规则改成 `**`，就能在所有网站上开启OneToc的目录

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/15317535/184103629-741def64-867e-4247-b879-4101cc42d5a3.png">

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/15317535/184105117-c111476a-3fa4-4748-905e-1e6018a8db9f.png">

**Comment by jierme** [comment]
> > 如题，例如 pubmed 上文献全文页面，要是能支持显示目录就好了。 举个例子：https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6742634/
> 
> @jierme 没有默认支持这些网站，但是可以通过修改匹配规则支持


谢谢你的回复，我应该说得再仔细一些。目前的目录识别在这类期刊文献网站上好像有一点点问题，目录显示不是很正确。会错误地把作者名字也当成目录，有一些子目录却又识别不出来，如果完善一下对这类网站格式的识别率就更好用了~

**Comment by Whilconn** [comment]
> 谢谢你的回复，我应该说得再仔细一些。目前的目录识别在这类期刊文献网站上好像有一点点问题，目录显示不是很正确。会错误地把作者名字也当成目录，有一些子目录却又识别不出来，如果完善一下对这类网站格式的识别率就更好用了~

了解，这两天我抽时间优化下目录解析的逻辑

**Comment by Whilconn** [comment]
> 谢谢你的回复，我应该说得再仔细一些。目前的目录识别在这类期刊文献网站上好像有一点点问题，目录显示不是很正确。会错误地把作者名字也当成目录，有一些子目录却又识别不出来，如果完善一下对这类网站格式的识别率就更好用了~

@jierme  目录解析的逻辑已经优化，发了一个新版本[v1.0.3](https://github.com/Whilconn/one-toc/releases/tag/v1.0.3)。
新版本已经提交Edge审核，要等两天才能更新，急用的话可以先下载zip使用。

**Comment by jierme** [comment]
感谢开发者为我们带来这么好用的插件~

**Comment by Whilconn** [comment]
> 感谢开发者为我们带来这么好用的插件~

哈哈客气，这个插件原本是自用的，我也很高兴它能帮到你
