### ISSUE TITLE
是否可以考虑增加将目录固定在左侧或右侧的功能？

### ISSUE THREAD

**Issue by dbcoffee** [Whilconn/one-toc#4]
相当于将目录固定在左侧或右侧，网页原有内容（宽度）自动向右或向左减少，避免目录挡住网页的内容。这样对本地markdown可能会更友好。

**Comment by Whilconn** [comment]
这个功能已经在[计划中](./1)，争取10月底前上

**Comment by Whilconn** [comment]
@dbcoffee 内嵌模式的版本可以体验了 [v1.2.0-alpha](https://github.com/Whilconn/one-toc/releases/tag/v1.2.0-alpha)
