### ISSUE TITLE
是否可以增加对本地页面（html）的支持？

### ISSUE THREAD

**Issue by dbcoffee** [Whilconn/one-toc#5]
在content_scripts中增加 file:///* 完成对本地html文件的支持。

```
 "content_scripts": [
    {
      "matches": [
        "*://*/*",
        "file:///*" 
      ]
    }
```

**Comment by Whilconn** [comment]
下个版本调整为 `"matches": ["<all_urls>"]` 

急用建议自行修改manifest.json配置

另外可以考虑使用轻量http服务器，比如[http-server](https://github.com/http-party/http-server)，命令行启动，自动遍历目录文件

也可以考虑使用 vscode + live server，附带实时刷新，遍历目录功能
