### ISSUE TITLE
目录抓取不全。

### ISSUE THREAD

**Issue by dbcoffee** [Whilconn/one-toc#7]
html本地打开后目录中只有   “4 模型探索”，期待解决。

html显示如下：

<!DOCTYPE html>

<html style="scroll-behavior: auto;"><head></head>

<body class="toc-embed-mod">

<section class="main-content">

<div id="读取数据配置" class="section level1" number="1">
<h1><span class="header-section-number">1</span> 读取数据、配置</h1>
</div>

<div id="数据清洗" class="section level1" number="2">
<h1 id="toc-anchor-0" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">2</span> 数据清洗</h1>
</div>

<div id="基线资料均衡性比较" class="section level1" number="3">
<h1 id="toc-anchor-1" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">3</span>
基线资料（均衡性比较）</h1>
</div>

<div id="模型探索" class="section level1" number="4">
<h1 id="toc-anchor-2" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">4</span> 模型探索</h1>
</div>
</section>

</body></html>

html代码如下：
```
<!DOCTYPE html>

<html style="scroll-behavior: auto;"><head></head>

<body class="toc-embed-mod">


<section class="main-content">

<div id="读取数据配置" class="section level1" number="1">
<h1><span class="header-section-number">1</span> 读取数据、配置</h1>
</div>

<div id="数据清洗" class="section level1" number="2">
<h1 id="toc-anchor-0" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">2</span> 数据清洗</h1>
</div>

<div id="基线资料均衡性比较" class="section level1" number="3">
<h1 id="toc-anchor-1" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">3</span>
基线资料（均衡性比较）</h1>
</div>

<div id="模型探索" class="section level1" number="4">
<h1 id="toc-anchor-2" toc-level="0" class="" style="scroll-margin-top: 0px; scroll-padding-top: 0px;"><span class="header-section-number">4</span> 模型探索</h1>
</div>
</section>

</body></html>
```

**Comment by Whilconn** [comment]
这个问题修复会跟下个版本一起发布

**Comment by Whilconn** [comment]
问题已经修复，把插件更新到 `1.3.0`，在当前页面打开插件就能看到效果
