### ISSUE TITLE
请问浮动模式可不可以在“设置”中增加上下左右四个选项啊？

### ISSUE THREAD

**Issue by zmh908264302** [Whilconn/one-toc#8]
@Whilconn 请问浮动模式可不可以在“设置”中增加上下左右四个选项啊？这样可以方便不同习惯的用户。

**Comment by Whilconn** [comment]
左右浮动我能理解，上下好像有点少见，目前还没见过目录在下方的设计。

左右浮动预计在国庆前后的版本支持。
